### PR TITLE
Show PMD violations overview/outline views when checking code

### PR DESCRIPTION
**Pull request by pkrall520**
Add two new options under General options.
"Show PMD Violations overview when checking code"
'"Show PMD Violations outline when checking code"

These options will open the view that they refer to rather than taking the user to a new perspective. 

image

### CODE REVIEW

**Comment by pkrall520** [comment]
I don't speak French, so I used google translator to create the French version. I know that the translator has some issues, but I have no way of validating at this time.

**Comment by adangel** [comment]
@pkrall520 I've tested your change and it works, as long as you execute the PMD check via the project's context menu "PMD -> Check Code". If the PMD check is executed via the builder (auto build enabled) or after save, nothing happens.

Is this, how it should be? I think, it's the same with the "Show PMD Perspective", so it's consistent with that...

**Comment by pkrall520** [comment]
@adangel Yeah It is based on the "Show PMD Perspective". I think how it is working is how it should work. I don't think we would want thee views popping up every time someone saves a file, but if we do, it should be a quick change

**Comment by adangel** [comment]
Merged :tada: Thanks for your contribution!

**Pull request merged**
